### ISSUE TITLE
25g "limit" on ADXL375

### ISSUE THREAD

**Issue by marshallmassengill** [adafruit/Adafruit_CircuitPython_ADXL37x#4]
Just FYI, it seems like there is a limit in place with the default/example code.

The ADI forums have a couple posts explaining it:
https://ez.analog.com/mems/f/q-a/89015/adxl-375-limit-at-25g
https://ez.analog.com/mems/f/q-a/85937/adxl375-saturating-at-25g

The core issue is that the default data in the DATA_FORMAT register doesn't align with what it needs to align with to give full 200g values and it appears like clipping/saturation at 25g.

**Comment by marshallmassengill** [comment]
I'm also guessing this is an issue for your Arduino example code, which uses SPI.

**Comment by FoamyGuy** [comment]
I think this could be resolved by #7, the range can now be set and there are constants for the different available options including 200g. 

Please give that a try and if there are still issues with the acceleration readings we can re-open this.
